--   ======================================================================================
--    AUTOGENERATED!!!! DO NOT EDIT!!!!
--   ======================================================================================

DROP TABLE IF EXISTS dv.customer_h;

CREATE TABLE dv.customer_h (
  customer_key         integer,
  customer_id          integer,
  load_dts             timestamp,
  rec_src              string,
);