--   ======================================================================================
--    AUTOGENERATED!!!! DO NOT EDIT!!!!
--   ======================================================================================

INSERT INTO dv.customer_h
SELECT
  customer_key
  ,customer_id
  ,load_dts
  ,rec_src
FROM (
  SELECT
    customer_key
    ,customer_id
    ,load_dts
    ,rec_src
    ,row_number() over(PARTITION BY customer_key ORDER BY load_dts asc) rn
  FROM (
    
    SELECT
      customer_id AS customer_key
      ,customer_id AS customer_id
      ,current_timestamp() AS load_dts
      ,'datalake.sales_line' AS rec_src
    FROM
      datalake.sales_line
    WHERE
      {{start_ts}} <= current_timestamp()
      AND current_timestamp() < {{end_ts}}
    UNION ALL
    SELECT
      customer_id AS customer_key
      ,customer_id AS customer_id
      ,current_timestamp() AS load_dts
      ,'datalake.customer' AS rec_src
    FROM
      datalake.customer
    WHERE
      {{start_ts}} <= current_timestamp()
      AND current_timestamp() < {{end_ts}}
  )
  q
  WHERE
    NOT EXISTS (
      SELECT 1
      FROM dv.customer_h t
      WHERE t.customer_key = q.customer_key
    )
)
WHERE rn = 1;