--   ======================================================================================
--    AUTOGENERATED!!!! DO NOT EDIT!!!!
--   ======================================================================================

DROP VIEW IF EXISTS dv.customer_h;

CREATE VIEW dv.customer_h
AS
SELECT
  customer_key
  ,customer_id
  ,load_dts
  ,rec_src
FROM (
  SELECT
    customer_key
    ,customer_id
    ,load_dts
    ,rec_src
    ,row_number() over(PARTITION BY customer_key ORDER BY load_dts asc) rn
  FROM (
    
    SELECT
      customer_id AS customer_key
      ,customer_id AS customer_id
      ,current_timestamp() AS load_dts
      ,'datalake.sales_line' AS rec_src
    FROM
      datalake.sales_line
    UNION ALL
    SELECT
      customer_id AS customer_key
      ,customer_id AS customer_id
      ,current_timestamp() AS load_dts
      ,'datalake.customer' AS rec_src
    FROM
      datalake.customer
  )
)
WHERE rn = 1;