--   ======================================================================================
--    AUTOGENERATED!!!! DO NOT EDIT!!!!
--   ======================================================================================

INSERT INTO dv.customer_main_s
SELECT
  customer_key
  ,max(load_dts) AS load_dts
  ,effective_ts
  ,first_name
  ,last_name
  ,email_address
  ,home_phone
  ,rec_src
FROM (
  
  SELECT
    customer_id AS customer_key
    ,current_timestamp() AS load_dts
    ,date AS effective_ts
    ,first_name AS first_name
    ,last_name AS last_name
    ,email AS email_address
    ,cell_number AS home_phone
    ,'datalake.customer' AS rec_src
  FROM
    datalake.customer
  WHERE
    {{start_ts}} <= current_timestamp()
    AND current_timestamp() < {{end_ts}}
)
q
WHERE
  NOT EXISTS (
    SELECT 1
    FROM dv.customer_main_s t
    WHERE t.customer_key = q.customer_key
      AND t.effective_ts = q.effective_ts
      AND t.first_name = q.first_name
      AND t.last_name = q.last_name
      AND t.email_address = q.email_address
      AND t.home_phone = q.home_phone
  )
GROUP BY
  customer_key
  ,effective_ts
  ,first_name
  ,last_name
  ,email_address
  ,home_phone
  ,rec_src;