--   ======================================================================================
--    AUTOGENERATED!!!! DO NOT EDIT!!!!
--   ======================================================================================

DROP TABLE IF EXISTS dv.customer_main_s;

CREATE TABLE dv.customer_main_s (
  customer_key         integer,
  load_dts             timestamp,
  effective_ts         timestamp,
  first_name           string,
  last_name            string,
  email_address        string,
  home_phone           string,
  rec_src              string,
);