--   ======================================================================================
--    AUTOGENERATED!!!! DO NOT EDIT!!!!
--   ======================================================================================

DROP VIEW IF EXISTS dv.product_h;

CREATE VIEW dv.product_h
AS
SELECT
  product_key
  ,product_id
  ,load_dts
  ,rec_src
FROM (
  SELECT
    product_key
    ,product_id
    ,load_dts
    ,rec_src
    ,row_number() over(PARTITION BY product_key ORDER BY load_dts asc) rn
  FROM (
    
    SELECT
      product_id AS product_key
      ,product_id AS product_id
      ,current_timestamp() AS load_dts
      ,'datalake.sales_line' AS rec_src
    FROM
      datalake.sales_line
    UNION ALL
    SELECT
      product_id AS product_key
      ,product_id AS product_id
      ,current_timestamp() AS load_dts
      ,'datalake.product' AS rec_src
    FROM
      datalake.product
  )
)
WHERE rn = 1;