--   ======================================================================================
--    AUTOGENERATED!!!! DO NOT EDIT!!!!
--   ======================================================================================

DROP TABLE IF EXISTS dv.product_main_s;

CREATE TABLE dv.product_main_s (
  product_key          integer,
  load_dts             timestamp,
  effective_ts         timestamp,
  product_name         string,
  product_color        string,
  rec_src              string,
);