--   ======================================================================================
--    AUTOGENERATED!!!! DO NOT EDIT!!!!
--   ======================================================================================

INSERT INTO dv.product_h
SELECT
  product_key
  ,product_id
  ,load_dts
  ,rec_src
FROM (
  SELECT
    product_key
    ,product_id
    ,load_dts
    ,rec_src
    ,row_number() over(PARTITION BY product_key ORDER BY load_dts asc) rn
  FROM (
    
    SELECT
      product_id AS product_key
      ,product_id AS product_id
      ,current_timestamp() AS load_dts
      ,'datalake.sales_line' AS rec_src
    FROM
      datalake.sales_line
    WHERE
      {{start_ts}} <= current_timestamp()
      AND current_timestamp() < {{end_ts}}
    UNION ALL
    SELECT
      product_id AS product_key
      ,product_id AS product_id
      ,current_timestamp() AS load_dts
      ,'datalake.product' AS rec_src
    FROM
      datalake.product
    WHERE
      {{start_ts}} <= current_timestamp()
      AND current_timestamp() < {{end_ts}}
  )
  q
  WHERE
    NOT EXISTS (
      SELECT 1
      FROM dv.product_h t
      WHERE t.product_key = q.product_key
    )
)
WHERE rn = 1;