--   ======================================================================================
--    AUTOGENERATED!!!! DO NOT EDIT!!!!
--   ======================================================================================

INSERT INTO dv.product_main_s
SELECT
  product_key
  ,max(load_dts) AS load_dts
  ,effective_ts
  ,product_name
  ,product_color
  ,rec_src
FROM (
  
  SELECT
    product_id AS product_key
    ,current_timestamp() AS load_dts
    ,date AS effective_ts
    ,product_name AS product_name
    ,color AS product_color
    ,'datalake.product' AS rec_src
  FROM
    datalake.product
  WHERE
    {{start_ts}} <= current_timestamp()
    AND current_timestamp() < {{end_ts}}
)
q
WHERE
  NOT EXISTS (
    SELECT 1
    FROM dv.product_main_s t
    WHERE t.product_key = q.product_key
      AND t.effective_ts = q.effective_ts
      AND t.product_name = q.product_name
      AND t.product_color = q.product_color
  )
GROUP BY
  product_key
  ,effective_ts
  ,product_name
  ,product_color
  ,rec_src;