--   ======================================================================================
--    AUTOGENERATED!!!! DO NOT EDIT!!!!
--   ======================================================================================

DROP TABLE IF EXISTS dv.product_h;

CREATE TABLE dv.product_h (
  product_key          integer,
  product_id           integer,
  load_dts             timestamp,
  rec_src              string,
);