--   ======================================================================================
--    AUTOGENERATED!!!! DO NOT EDIT!!!!
--   ======================================================================================

DROP VIEW IF EXISTS dv.product_main_s;

CREATE VIEW dv.product_main_s
AS
SELECT
  product_key
  ,max(load_dts) AS load_dts
  ,effective_ts
  ,product_name
  ,product_color
  ,rec_src
FROM (
  
  SELECT
    product_id AS product_key
    ,current_timestamp() AS load_dts
    ,date AS effective_ts
    ,product_name AS product_name
    ,color AS product_color
    ,'datalake.product' AS rec_src
  FROM
    datalake.product
)
GROUP BY
  product_key
  ,effective_ts
  ,product_name
  ,product_color
  ,rec_src;