--   ======================================================================================
--    AUTOGENERATED!!!! DO NOT EDIT!!!!
--   ======================================================================================

DROP TABLE IF EXISTS dv.sale_line_l;

CREATE TABLE dv.sale_line_l (
  sale_line_l_key      integer,
  sale_line_key        integer,
  customer_key         integer,
  product_key          integer,
  load_dts             timestamp,
  rec_src              string,
);