--   ======================================================================================
--    AUTOGENERATED!!!! DO NOT EDIT!!!!
--   ======================================================================================

DROP TABLE IF EXISTS dv.sale_line_h;

CREATE TABLE dv.sale_line_h (
  sale_line_key        integer,
  sale_line_id         integer,
  load_dts             timestamp,
  rec_src              string,
);