--   ======================================================================================
--    AUTOGENERATED!!!! DO NOT EDIT!!!!
--   ======================================================================================

INSERT INTO dv.sale_line_h
SELECT
  sale_line_key
  ,sale_line_id
  ,load_dts
  ,rec_src
FROM (
  SELECT
    sale_line_key
    ,sale_line_id
    ,load_dts
    ,rec_src
    ,row_number() over(PARTITION BY sale_line_key ORDER BY load_dts asc) rn
  FROM (
    
    SELECT
      sales_line_id AS sale_line_key
      ,sales_line_id AS sale_line_id
      ,current_timestamp() AS load_dts
      ,'datalake.sales_line' AS rec_src
    FROM
      datalake.sales_line
    WHERE
      {{start_ts}} <= current_timestamp()
      AND current_timestamp() < {{end_ts}}
  )
  q
  WHERE
    NOT EXISTS (
      SELECT 1
      FROM dv.sale_line_h t
      WHERE t.sale_line_key = q.sale_line_key
    )
)
WHERE rn = 1;