--   ======================================================================================
--    AUTOGENERATED!!!! DO NOT EDIT!!!!
--   ======================================================================================

DROP VIEW IF EXISTS dv.sale_line_h;

CREATE VIEW dv.sale_line_h
AS
SELECT
  sale_line_key
  ,sale_line_id
  ,load_dts
  ,rec_src
FROM (
  SELECT
    sale_line_key
    ,sale_line_id
    ,load_dts
    ,rec_src
    ,row_number() over(PARTITION BY sale_line_key ORDER BY load_dts asc) rn
  FROM (
    
    SELECT
      sales_line_id AS sale_line_key
      ,sales_line_id AS sale_line_id
      ,current_timestamp() AS load_dts
      ,'datalake.sales_line' AS rec_src
    FROM
      datalake.sales_line
  )
)
WHERE rn = 1;