--   ======================================================================================
--    AUTOGENERATED!!!! DO NOT EDIT!!!!
--   ======================================================================================

DROP VIEW IF EXISTS dv.sale_line_l;

CREATE VIEW dv.sale_line_l
AS
SELECT
  sale_line_l_key
  ,sale_line_key
  ,customer_key
  ,product_key
  ,load_dts
  ,rec_src
FROM (
  SELECT
    sale_line_l_key
    ,sale_line_key
    ,customer_key
    ,product_key
    ,load_dts
    ,rec_src
    ,row_number() over(PARTITION BY sale_line_l_key ORDER BY load_dts asc) rn
  FROM (
    
    SELECT
      sales_line_id || '|' || customer_id || '|' || product_id AS sale_line_l_key
      ,sales_line_id AS sale_line_key
      ,customer_id AS customer_key
      ,product_id AS product_key
      ,current_timestamp() AS load_dts
      ,'datalake.sales_line' AS rec_src
    FROM datalake.sales_line
  )
)
WHERE rn = 1;