--   ======================================================================================
--    AUTOGENERATED!!!! DO NOT EDIT!!!!
--   ======================================================================================

DROP TABLE IF EXISTS dv.sale_line_main_s;

CREATE TABLE dv.sale_line_main_s (
  sale_line_key        integer,
  load_dts             timestamp,
  effective_ts         timestamp,
  item_cost            integer,
  item_quantity        integer,
  rec_src              string,
);