--   ======================================================================================
--    AUTOGENERATED!!!! DO NOT EDIT!!!!
--   ======================================================================================

INSERT INTO dv.sale_line_l
SELECT
  sale_line_l_key
  ,sale_line_key
  ,customer_key
  ,product_key
  ,load_dts
  ,rec_src
FROM (
  SELECT
    sale_line_l_key
    ,sale_line_key
    ,customer_key
    ,product_key
    ,load_dts
    ,rec_src
    ,row_number() over(PARTITION BY sale_line_l_key ORDER BY load_dts asc) rn
  FROM (
    
    SELECT
      sales_line_id || '|' || customer_id || '|' || product_id AS sale_line_l_key
      ,sales_line_id AS sale_line_key
      ,customer_id AS customer_key
      ,product_id AS product_key
      ,current_timestamp() AS load_dts
      ,'datalake.sales_line' AS rec_src
    FROM datalake.sales_line
    WHERE       {{start_ts}} <= current_timestamp()
      AND current_timestamp() < {{end_ts}}
  )
  q
  WHERE
    NOT EXISTS (
      SELECT 1
      FROM dv.sale_line_l t
      WHERE t.sale_line_l_key = q.sale_line_l_key
    )
)
WHERE rn = 1;